# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-07 10:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_auto_20180707_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopmodel',
            name='close_at',
            field=models.CharField(blank=True, help_text='In HH:MM format.', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='shopmodel',
            name='open_at',
            field=models.CharField(blank=True, help_text='In HH:MM format.', max_length=5, null=True),
        ),
    ]
