# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-03 12:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='category',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='evaluation',
            field=models.TextField(default='Your opinion goes here...', verbose_name='Your opinion:'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productmodel',
            name='mark',
            field=models.FloatField(default='6', verbose_name='Your mark:'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productmodel',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
