# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-07 09:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
        ('main', '0003_productmodel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shops.ShopModel'),
        ),
    ]
